on:
  release:
    types: [published]

name: Upload Release Asset
jobs:
  build:
    name: Build and Package 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Build and package app
        run: |
          mkdir out
          cp README.md out/
          cp index.html out/
          echo 'Hello, world!' >> out/hello.txt
          tar cvfz build.tar.gz out/
      - name: Archive Development Artifact
        uses: actions/upload-artifact@master
        with:
          name: main-out
          path: build.tar.gz
          retention-days: 3

  deploy:
    name: Deploy and Upload Release Asset
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: main-out
      - name: Extract Artifact Files
        run: tar -zxvf build.tar.gz
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          publish_branch: gh-pages
      - name: Attach Artifact to Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
