# .github/workflows/scheduled-builds.yml
name: Say Hello and Cheese

on:
  schedule:
    # Runs "At minute 0 past every 3rd hour."
    - cron: '0 */3 * * *'
    # Runs "At minute 0 past every hour."
    - cron: '0 */1 * * *'

jobs:
  say-hello:
    name: Say Hello
    runs-on: ubuntu-latest
    steps:
      - name: Say Hellooo
        if: github.event.schedule == '0 */3 * * *'
        run: echo "Hello, world!"

  say-cheese:
    name: Say Cheese
    runs-on: ubuntu-latest
    steps:
      - name: Say Cheese!
        if: github.event.schedule == '0 */1 * * *'
        run: echo "Cheese! :)"
